-- 409_schema_export.sql — #409(b): export the LIVE database's schema so the
-- repo gets a baseline record (409_schema_baseline.sql) built from the live DB,
-- not from old downloads (handoff §3, §5 "extend from the LIVE object").
--
-- READ-ONLY. One SELECT, nothing written, nothing changed. Safe to run twice.
-- Run in: Supabase dashboard → SQL Editor → paste this whole file → Run.
-- The editor shows only the last statement's result (handoff §5), so this file
-- IS one statement. It returns ONE row:
--   objects  — how many DDL objects were exported
--   kb       — size of the dump
--   sections — the count per kind (table 16, function 23, …) to check against
--   dump     — the whole schema as one text cell
-- Then: Export → Download CSV, and ATTACH the .csv file to the chat. Don't
-- copy the grid as Markdown: that escapes | and possibly \ inside function
-- bodies and regexes, so the copy is no longer byte-exact.
--
-- 2026-09-24 rev: checks now come after functions (profiles' reserved-name
-- checks call display_name_is_reserved*()), pg_cron's pg_catalog schema is
-- dropped from its create line, and the sections column was added.
--
-- What it covers (the #409 scope: what a future pass would rebuild from):
--   extensions, sequences, public tables (columns, defaults, identity),
--   constraints (PK/unique/check/exclusion first, then foreign keys),
--   indexes, public functions + procedures (extension-owned excluded),
--   views + materialized views (with security_invoker etc.), triggers on
--   public tables AND triggers anywhere that call a public function (the
--   auth.users → profiles trigger), RLS enable/force, policies on public +
--   storage, table / column / function grants, and pg_cron jobs.
-- What it does NOT cover, on purpose: row data, one-shot data migrations
-- (405 gets its own record file), auth/storage internals Supabase owns,
-- Edge Functions (already in the repo as <function>-index.<ext>), secrets.

with
rel as (
  select c.oid, c.relname, c.relkind, c.relrowsecurity, c.relforcerowsecurity,
         c.relacl, c.reloptions
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind in ('r','p','v','m','S')
    and not exists (select 1 from pg_depend d
                    where d.classid = 'pg_class'::regclass and d.objid = c.oid and d.deptype = 'e')
),
fn as (
  select p.oid, p.proname, p.prokind, p.proacl,
         format('public.%I(%s)', p.proname, pg_get_function_identity_arguments(p.oid)) as sig
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.prokind in ('f','p')
    and not exists (select 1 from pg_depend d
                    where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')
),
out as (
  -- 01 extensions
  select 1 as ord, 0::bigint as k, 'extension' as section, e.extname::text as obj,
         case when en.nspname = 'pg_catalog'
              then format('create extension if not exists %I;', e.extname)
              else format('create extension if not exists %I with schema %I;', e.extname, en.nspname) end as ddl
  from pg_extension e join pg_namespace en on en.oid = e.extnamespace
  where e.extname <> 'plpgsql'

  union all
  -- 02 sequences, before the tables whose defaults call nextval() on them
  --    (identity-column sequences are left out: the table creates its own)
  select 2, r.oid::bigint, 'sequence', r.relname::text,
         format('create sequence if not exists public.%I;', r.relname)
  from rel r
  where r.relkind = 'S'
    and not exists (select 1 from pg_depend d
                    where d.classid = 'pg_class'::regclass and d.objid = r.oid and d.deptype = 'i')

  union all
  -- 03 tables
  select 3, r.oid::bigint, 'table', r.relname::text,
         format(E'create table public.%I (\n%s\n);', r.relname,
           (select string_agg(
                     format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
                       case a.attidentity when 'a' then ' generated always as identity'
                                          when 'd' then ' generated by default as identity' else '' end,
                       case when a.attgenerated = 's'
                              then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                            when ad.adbin is not null
                              then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                            else '' end,
                       case when a.attnotnull then ' not null' else '' end),
                     E',\n' order by a.attnum)
            from pg_attribute a
            left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
            where a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped))
  from rel r
  where r.relkind in ('r','p')

  union all
  -- 04 keys + exclusions, 05 foreign keys, 08 checks (a check can call a
  --    public function, so checks wait until the functions exist)
  select case co.contype when 'f' then 5 when 'c' then 8 else 4 end, co.oid::bigint, 'constraint',
         (r.relname || '.' || co.conname)::text,
         format('alter table public.%I add constraint %I %s;', r.relname, co.conname,
                pg_get_constraintdef(co.oid))
  from pg_constraint co
  join rel r on r.oid = co.conrelid
  where co.contype in ('p','u','c','f','x')

  union all
  -- 06 indexes not already created by a constraint
  select 6, i.indexrelid::bigint, 'index', ic.relname::text,
         pg_get_indexdef(i.indexrelid) || ';'
  from pg_index i
  join rel r on r.oid = i.indrelid
  join pg_class ic on ic.oid = i.indexrelid
  where not exists (select 1 from pg_constraint co where co.conindid = i.indexrelid)

  union all
  -- 07 functions + procedures (creation order)
  select 7, f.oid::bigint, 'function', f.sig,
         pg_get_functiondef(f.oid) || ';'
  from fn f

  union all
  -- 09 views + materialized views (creation order)
  select 9, r.oid::bigint, case r.relkind when 'm' then 'matview' else 'view' end, r.relname::text,
         case r.relkind
           when 'v' then format(E'create or replace view public.%I%s as\n%s', r.relname,
                          coalesce(' with (' || array_to_string(r.reloptions, ', ') || ')', ''),
                          pg_get_viewdef(r.oid, true))
           else format(E'create materialized view public.%I as\n%s\nwith no data;', r.relname,
                       rtrim(pg_get_viewdef(r.oid, true), ';'))
         end
  from rel r
  where r.relkind in ('v','m')

  union all
  -- 10 triggers: on public tables, or anywhere calling a public function
  select 10, t.oid::bigint, 'trigger', (tn.nspname || '.' || tc.relname || '.' || t.tgname)::text,
         pg_get_triggerdef(t.oid, true) || ';'
  from pg_trigger t
  join pg_class tc on tc.oid = t.tgrelid
  join pg_namespace tn on tn.oid = tc.relnamespace
  where not t.tgisinternal
    and (tn.nspname = 'public' or t.tgfoid in (select oid from fn))

  union all
  -- 11 row level security switches
  select 11, r.oid::bigint, 'rls', r.relname::text,
         format('alter table public.%I enable row level security;', r.relname)
         || case when r.relforcerowsecurity
                 then format(E'\nalter table public.%I force row level security;', r.relname) else '' end
  from rel r
  where r.relkind in ('r','p') and r.relrowsecurity

  union all
  -- 12 policies (public + storage)
  select 12, 0, 'policy', (pol.schemaname || '.' || pol.tablename || '.' || pol.policyname)::text,
         format('create policy %I on %I.%I as %s for %s to %s%s%s;',
                pol.policyname, pol.schemaname, pol.tablename, lower(pol.permissive), lower(pol.cmd),
                (select string_agg(case when x = 'public' then 'public' else quote_ident(x) end, ', ')
                   from unnest(pol.roles) x),
                coalesce(E'\n  using (' || pol.qual || ')', ''),
                coalesce(E'\n  with check (' || pol.with_check || ')', ''))
  from pg_policies pol
  where pol.schemaname in ('public','storage')

  union all
  -- 13 table / view / sequence grants (owner's own grants left out)
  select 13, r.oid::bigint, 'grant', r.relname::text,
         format('revoke all on %s public.%I from public, anon, authenticated, service_role;',
                case r.relkind when 'S' then 'sequence' else 'table' end, r.relname)
         || coalesce((select string_agg(format(E'\ngrant %s on %s public.%I to %s;',
                                          g.privs, case r.relkind when 'S' then 'sequence' else 'table' end,
                                          r.relname, g.who), '' order by g.who)
                      from (select case when a.grantee = 0 then 'public' else quote_ident(pg_get_userbyid(a.grantee)) end as who,
                                   string_agg(lower(a.privilege_type), ', ' order by a.privilege_type) as privs
                            from aclexplode(r.relacl) a
                            where a.grantee <> a.grantor
                            group by a.grantee) g), '')
  from rel r
  where r.relacl is not null

  union all
  -- 14 column-level grants
  select 14, r.oid::bigint, 'column grant', (r.relname || '.' || a.attname)::text,
         (select string_agg(format('grant %s (%I) on table public.%I to %s;', lower(x.privilege_type),
                                   a.attname, r.relname,
                                   case when x.grantee = 0 then 'public' else quote_ident(pg_get_userbyid(x.grantee)) end),
                            E'\n')
          from aclexplode(a.attacl) x where x.grantee <> x.grantor)
  from rel r
  join pg_attribute a on a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped
  where a.attacl is not null

  union all
  -- 15 function grants (NULL acl = the Postgres default: execute to PUBLIC)
  select 15, f.oid::bigint, 'function grant', f.sig,
         case when f.proacl is null
           then format('-- %s: default ACL (execute granted to PUBLIC)', f.sig)
           else format('revoke all on %s %s from public, anon, authenticated, service_role;',
                       case f.prokind when 'p' then 'procedure' else 'function' end, f.sig)
                || coalesce((select string_agg(format(E'\ngrant execute on %s %s to %s;',
                                                 case f.prokind when 'p' then 'procedure' else 'function' end,
                                                 f.sig,
                                                 case when a.grantee = 0 then 'public' else quote_ident(pg_get_userbyid(a.grantee)) end),
                                          '' order by a.grantee)
                             from aclexplode(f.proacl) a where a.grantee <> a.grantor), '')
         end
  from fn f

  union all
  -- 16 pg_cron jobs
  select 16, j.jobid::bigint, 'cron', j.jobname::text,
         format('select cron.schedule(%L, %L, %L);%s', j.jobname, j.schedule, j.command,
                case when j.active then '' else '  -- INACTIVE on export' end)
  from cron.job j
)
select count(*) as objects,
       round(sum(length(ddl)) / 1024.0) as kb,
       (select string_agg(section || ' ' || n, ', ' order by o)
          from (select section, min(ord) as o, count(*) as n from out group by section) t) as sections,
       string_agg(format(E'-- [%s] %s\n%s', section, obj, ddl), E'\n\n' order by ord, k, obj) as dump
from out;
